//Copy of script.js only css path is changed to booking wodget css
// Include CSS styles
const link = document.createElement('link');
link.rel = 'stylesheet';
link.type = 'text/css';
link.href = 'common.css'; // Replace 'styles.css' with the path to your CSS file
document.head.appendChild(link);

// HTML content for the modal
const modalHTML = `
<div id="myModal" class="modal">
    <div class="modal-content">
        <!-- Modal content goes here -->
    </div>
</div>
`;

// Add the modal HTML to the document body
document.body.insertAdjacentHTML('beforeend', modalHTML);


$(document).ready(function () {
    // Initialize Select2 for the city dropdowns
    $('.city-dropdown').select2({
        placeholder: 'Search for a city',
        allowClear: true // Enable clear option
    });

});


// JavaScript code for your webpage
function basicCheck() {
    var source = document.getElementById('source').value;
    var destination = document.getElementById('destination').value;

    if (!source || !destination) {
        // Display error modal
        var errorModal = document.getElementById('errorModal');
        errorModal.style.display = 'flex';
        return; // Stop execution if validation fails
    }
}

function submitBooking() {
    basicCheck();
    var roundOffDistance = calculateDistance()[1];

    var availableCabs = [
        { type: 'Hatchback', details: '3 seats, Non-AC, Economical', distance: roundOffDistance + ' Km', fare: calculatePrice()[2] + ' ₹' },
        { type: 'Sedan', details: '3 seats, AC, Comfortable', distance: roundOffDistance + ' Km', fare: calculatePrice()[0] + ' ₹' },
        { type: 'SUV', details: '6 seats, AC, Spacious', distance: roundOffDistance + ' Km', fare: calculatePrice()[1] + ' ₹' },
        { type: 'Force Traveller', details: '12 seats, AC, Mini-Bus', distance: roundOffDistance + ' Km', fare: calculatePrice()[3] + ' ₹' },
        { type: 'Self-Drive', details: 'For more details please call our support center.', distance: roundOffDistance + ' Km', fare: ' NA ₹' },
        // Add more cabs as needed
    ];

    // Display the modal
    var modal = document.getElementById('myModal');
    modal.style.display = 'flex';

    // Display the list of available cabs in the modal table
    var availableCabsBody = document.getElementById('availableCabsBody');
    availableCabsBody.innerHTML = '';

    availableCabs.forEach(cab => {
        var row = document.createElement('tr');

        var randomId = Math.random().toString(36).substring(7); // Generate a random ID
        var nameInputId = `${cab.type.toLowerCase()}_Type_${randomId}`;
        var mobileNumberInputId = `${cab.type.toLowerCase()}MobileNumber_${randomId}`;
        var confirmButtonId = `confirmButton_${randomId}`;

        row.innerHTML = `
    <td>${cab.type}</td>
    <td>${cab.details}</td>
    <td id>${cab.distance}</td>
    <td>${cab.fare}</td>
    <td>
        <input type="text" id="${nameInputId}" placeholder="Full Name *" maxlength="25" pattern="[A-Za-z ]+" title="Please enter only alphabets and limit to 25 characters" required />
        
        <input type="tel" id="${mobileNumberInputId}" placeholder="10 digit Mobile Number *" maxlength="10" pattern="[0-9]{1,10}" title="Please enter a valid 1 to 12-digit mobile number" inputmode="numeric" pattern="[0-9]*" required />
        <button id="${confirmButtonId}" onclick="confirmBooking('${cab.type}', '${cab.fare}', '${nameInputId}', '${mobileNumberInputId}','${cab.distance}')" disabled>Confirm Booking</button>
    </td>
`;
        availableCabsBody.appendChild(row);

        // Add input event listeners to enable/disable the button based on input validity
        var nameInput = document.getElementById(nameInputId);
        var mobileNumberInput = document.getElementById(mobileNumberInputId);
        var confirmButton = document.getElementById(confirmButtonId);

        nameInput.addEventListener('input', updateButtonState);
        mobileNumberInput.addEventListener('input', updateButtonState);

        function updateButtonState() {
            confirmButton.disabled = !(nameInput.validity.valid && mobileNumberInput.validity.valid);
        }
    });
}


function calculatePrice() {

    // Example: Assume a base price per km
    const hatchBack = 10;
    const sedan = 14;
    const suv = 16;
    const tempo_12 = 20;

    var distance = calculateDistance();
    var roundOffDistance = distance[0];
    var totalDistance = distance[1];



    // Calculate total price
    const sedanPrice = roundOffDistance * sedan;
    const suvPrice = roundOffDistance * suv;
    const hatchPrice = roundOffDistance * hatchBack;
    const tempo_12_price = roundOffDistance * tempo_12

    calculatedPrice = [sedanPrice, suvPrice, hatchPrice, tempo_12_price];

    return calculatedPrice;
}

function calculateDistance() {
    const sourceCity = document.getElementById('source').value;
    const destinationCity = document.getElementById('destination').value;

    // Basic input validation
    if (!sourceCity || !destinationCity) {
        displayError('Please fill in all the fields.');
        return;
    }
    const predefinedDistances = {
        'Mumbai': {
            'Mumbai': 0,
            'Pune': 150,
            'Nagpur': 850,
            'Thane': 30,
            'Nashik': 200,
            'Aurangabad': 350,
            'Solapur': 500,
            'Kolhapur': 380,
            'Amravati': 720,
            'Navi Mumbai': 35,
            'Akola': 640,
            'Jalgaon': 410,
            'Latur': 520,
            'Dhule': 335,
            'Nanded': 560,
            'Sangli': 390,
            'Malegaon': 270,
            'Jalna': 415,
            'Chandrapur': 840,
            'Bhiwandi': 55,
            'Parbhani': 490,
            'Ichalkaranji': 395,
            'Panvel': 50,
            'Satara': 250,
            'Beed': 390,
            'Yavatmal': 680,
            'Osmanabad': 420,
            'Ratnagiri': 330,
            'Wardha': 770,
            'Buldhana': 550,
            'Gondia': 930,
            'Hingoli': 590,
            'Khopoli': 80,
            'Nandurbar': 420,
            'Palghar': 115,
            'Washim': 660,
            'Karad': 290,
            'Baramati': 120,
            'Chimur': 720,
            'Deolali': 165,
            'Gangapur': 290,
            'Junnar': 160,
            'Kamthi': 870,
            'Panjim': 590
        },
        'Pune': {
            'Pune': 0,
            'Mumbai': 150,
            'Nagpur': 700,
            'Thane': 150,
            'Nashik': 200,
            'Aurangabad': 250,
            'Solapur': 250,
            'Amravati': 800,
            'Navi Mumbai': 160,
            'Kolhapur': 400,
            'Akola': 600,
            'Jalgaon': 450,
            'Latur': 300,
            'Ratnagiri': 400,
            'Dhule': 370,
            'Nanded': 470,
            'Sangli': 230,
            'Malegaon': 350,
            'Jalna': 290,
            'Chandrapur': 770,
            'Bhiwandi': 150,
            'Parbhani': 430,
            'Ichalkaranji': 240,
            'Panvel': 140,
            'Satara': 110,
            'Beed': 390,
            'Yavatmal': 660,
            'Osmanabad': 250,
            'Wardha': 750,
            'Buldhana': 540,
            'Gondia': 860,
            'Hingoli': 550,
            'Khopoli': 120,
            'Nandurbar': 480,
            'Palghar': 170,
            'Washim': 620,
            'Karad': 200,
            'Baramati': 80,
            'Chimur': 720,
            'Deolali': 210,
            'Gangapur': 200,
            'Junnar': 100,
            'Kamthi': 790,
            'Panjim': 440,
        },
        'Nagpur': {
            'Nagpur': 0,
            'Mumbai': 850,
            'Pune': 700,
            'Thane': 880,
            'Nashik': 680,
            'Aurangabad': 480,
            'Solapur': 750,
            'Kolhapur': 900,
            'Amravati': 160,
            'Navi Mumbai': 870,
            'Akola': 250,
            'Jalgaon': 460,
            'Latur': 570,
            'Ratnagiri': 1100,
            'Dhule': 770,
            'Nanded': 270,
            'Sangli': 970,
            'Malegaon': 770,
            'Jalna': 530,
            'Chandrapur': 140,
            'Bhiwandi': 920,
            'Parbhani': 340,
            'Ichalkaranji': 970,
            'Panvel': 890,
            'Satara': 1050,
            'Beed': 670,
            'Yavatmal': 150,
            'Osmanabad': 560,
            'Wardha': 75,
            'Buldhana': 660,
            'Gondia': 170,
            'Hingoli': 570,
            'Khopoli': 890,
            'Nandurbar': 640,
            'Palghar': 910,
            'Washim': 170,
            'Karad': 900,
            'Baramati': 810,
            'Chimur': 160,
            'Deolali': 890,
            'Gangapur': 930,
            'Junnar': 930,
            'Kamthi': 20,
            'Panjim': 1050,
        },
        'Nashik': {
            'Nashik': 0,
            'Mumbai': 200,
            'Pune': 200,
            'Thane': 200,
            'Nagpur': 680,
            'Aurangabad': 250,
            'Solapur': 500,
            'Kolhapur': 800,
            'Amravati': 770,
            'Navi Mumbai': 210,
            'Akola': 750,
            'Jalgaon': 200,
            'Latur': 500,
            'Ratnagiri': 880,
            'Dhule': 200,
            'Nanded': 770,
            'Sangli': 900,
            'Malegaon': 570,
            'Jalna': 490,
            'Chandrapur': 810,
            'Bhiwandi': 200,
            'Parbhani': 570,
            'Ichalkaranji': 890,
            'Panvel': 220,
            'Satara': 440,
            'Beed': 620,
            'Yavatmal': 900,
            'Osmanabad': 470,
            'Wardha': 650,
            'Buldhana': 690,
            'Gondia': 900,
            'Hingoli': 400,
            'Khopoli': 350,
            'Nandurbar': 750,
            'Palghar': 150,
            'Washim': 800,
            'Karad': 550,
            'Baramati': 330,
            'Chimur': 610,
            'Deolali': 50,
            'Gangapur': 350,
            'Junnar': 250,
            'Kamthi': 840,
            'Panjim': 660,
        },
        'Thane': {
            'Thane': 0,
            'Mumbai': 30,
            'Pune': 150,
            'Nagpur': 880,
            'Nashik': 200,
            'Aurangabad': 600,
            'Solapur': 800,
            'Kolhapur': 900,
            'Amravati': 890,
            'Navi Mumbai': 40,
            'Akola': 800,
            'Jalgaon': 250,
            'Latur': 750,
            'Ratnagiri': 920,
            'Dhule': 300,
            'Nanded': 890,
            'Sangli': 920,
            'Malegaon': 570,
            'Jalna': 610,
            'Chandrapur': 810,
            'Bhiwandi': 30,
            'Parbhani': 780,
            'Ichalkaranji': 870,
            'Panvel': 50,
            'Satara': 420,
            'Beed': 660,
            'Yavatmal': 940,
            'Osmanabad': 580,
            'Wardha': 750,
            'Buldhana': 750,
            'Gondia': 930,
            'Hingoli': 480,
            'Khopoli': 70,
            'Nandurbar': 850,
            'Palghar': 30,
            'Washim': 900,
            'Karad': 550,
            'Baramati': 330,
            'Chimur': 640,
            'Deolali': 60,
            'Gangapur': 310,
            'Junnar': 250,
            'Kamthi': 890,
            'Panjim': 580,
        },
        'Aurangabad': {
            'Aurangabad': 0,
            'Mumbai': 350,
            'Pune': 250,
            'Nagpur': 480,
            'Thane': 600,
            'Nashik': 250,
            'Solapur': 410,
            'Kolhapur': 420,
            'Amravati': 340,
            'Navi Mumbai': 615,
            'Akola': 370,
            'Jalgaon': 250,
            'Latur': 250,
            'Dhule': 500,
            'Nanded': 270,
            'Sangli': 500,
            'Malegaon': 570,
            'Jalna': 150,
            'Chandrapur': 590,
            'Bhiwandi': 520,
            'Parbhani': 210,
            'Ichalkaranji': 500,
            'Panvel': 610,
            'Satara': 330,
            'Beed': 320,
            'Yavatmal': 440,
            'Osmanabad': 260,
            'Ratnagiri': 690,
            'Wardha': 600,
            'Buldhana': 390,
            'Gondia': 580,
            'Hingoli': 390,
            'Khopoli': 590,
            'Nandurbar': 560,
            'Palghar': 570,
            'Washim': 500,
            'Karad': 310,
            'Baramati': 390,
            'Chimur': 430,
            'Deolali': 620,
            'Gangapur': 480,
            'Junnar': 520,
            'Kamthi': 590,
            'Panjim': 560,
        },
        'Solapur': {
            'Solapur': 0,
            'Mumbai': 500,
            'Pune': 250,
            'Nagpur': 750,
            'Thane': 800,
            'Nashik': 500,
            'Aurangabad': 410,
            'Kolhapur': 240,
            'Amravati': 700,
            'Navi Mumbai': 815,
            'Akola': 590,
            'Jalgaon': 550,
            'Latur': 250,
            'Dhule': 635,
            'Nanded': 270,
            'Sangli': 530,
            'Malegaon': 620,
            'Jalna': 260,
            'Chandrapur': 590,
            'Bhiwandi': 580,
            'Parbhani': 310,
            'Ichalkaranji': 530,
            'Panvel': 830,
            'Satara': 300,
            'Beed': 270,
            'Yavatmal': 430,
            'Osmanabad': 110,
            'Ratnagiri': 580,
            'Wardha': 750,
            'Buldhana': 290,
            'Gondia': 780,
            'Hingoli': 180,
            'Khopoli': 820,
            'Nandurbar': 420,
            'Palghar': 690,
            'Washim': 780,
            'Karad': 160,
            'Baramati': 350,
            'Chimur': 590,
            'Deolali': 740,
            'Gangapur': 510,
            'Junnar': 340,
            'Kamthi': 100,
            'Panjim': 485,
        },
        'Kolhapur': {
            'Kolhapur': 0,
            'Mumbai': 380,
            'Pune': 400,
            'Nagpur': 900,
            'Thane': 900,
            'Nashik': 800,
            'Aurangabad': 420,
            'Solapur': 240,
            'Amravati': 860,
            'Navi Mumbai': 905,
            'Akola': 760,
            'Jalgaon': 850,
            'Latur': 680,
            'Dhule': 560,
            'Nanded': 670,
            'Sangli': 240,
            'Malegaon': 550,
            'Jalna': 560,
            'Chandrapur': 710,
            'Bhiwandi': 810,
            'Parbhani': 670,
            'Ichalkaranji': 260,
            'Panvel': 870,
            'Satara': 130,
            'Beed': 570,
            'Yavatmal': 820,
            'Osmanabad': 330,
            'Ratnagiri': 180,
            'Wardha': 910,
            'Buldhana': 470,
            'Gondia': 1000,
            'Hingoli': 680,
            'Khopoli': 890,
            'Nandurbar': 840,
            'Palghar': 890,
            'Washim': 850,
            'Karad': 200,
            'Baramati': 480,
            'Chimur': 720,
            'Deolali': 870,
            'Gangapur': 640,
            'Junnar': 470,
            'Kamthi': 930,
            'Panjim': 200,
        },
        'Amravati': {
            'Amravati': 0,
            'Mumbai': 720,
            'Pune': 800,
            'Nagpur': 160,
            'Thane': 890,
            'Nashik': 770,
            'Aurangabad': 340,
            'Solapur': 700,
            'Kolhapur': 860,
            'Navi Mumbai': 880,
            'Akola': 100,
            'Jalgaon': 400,
            'Latur': 470,
            'Dhule': 490,
            'Nanded': 360,
            'Sangli': 750,
            'Malegaon': 620,
            'Jalna': 260,
            'Chandrapur': 200,
            'Bhiwandi': 920,
            'Parbhani': 310,
            'Ichalkaranji': 880,
            'Panvel': 940,
            'Satara': 780,
            'Beed': 510,
            'Yavatmal': 150,
            'Osmanabad': 590,
            'Ratnagiri': 1010,
            'Wardha': 150,
            'Buldhana': 180,
            'Gondia': 460,
            'Hingoli': 540,
            'Khopoli': 920,
            'Nandurbar': 690,
            'Palghar': 935,
            'Washim': 180,
            'Karad': 860,
            'Baramati': 800,
            'Chimur': 170,
            'Deolali': 910,
            'Gangapur': 950,
            'Junnar': 870,
            'Kamthi': 130,
            'Panjim': 1245,
        },
        'Navi Mumbai': {
            'Navi Mumbai': 0,
            'Mumbai': 35,
            'Pune': 160,
            'Nagpur': 870,
            'Thane': 40,
            'Nashik': 210,
            'Aurangabad': 615,
            'Solapur': 815,
            'Kolhapur': 905,
            'Amravati': 880,
            'Akola': 870,
            'Jalgaon': 690,
            'Latur': 750,
            'Dhule': 670,
            'Nanded': 670,
            'Sangli': 880,
            'Malegaon': 590,
            'Jalna': 810,
            'Chandrapur': 850,
            'Bhiwandi': 15,
            'Parbhani': 690,
            'Ichalkaranji': 880,
            'Panvel': 40,
            'Satara': 830,
            'Beed': 650,
            'Yavatmal': 920,
            'Osmanabad': 730,
            'Ratnagiri': 960,
            'Wardha': 890,
            'Buldhana': 820,
            'Gondia': 960,
            'Hingoli': 710,
            'Khopoli': 70,
            'Nandurbar': 910,
            'Palghar': 70,
            'Washim': 800,
            'Karad': 890,
            'Baramati': 710,
            'Chimur': 890,
            'Deolali': 30,
            'Gangapur': 760,
            'Junnar': 160,
            'Kamthi': 890,
            'Panjim': 590,
        },
        'Akola': {
            'Akola': 0,
            'Mumbai': 640,
            'Pune': 600,
            'Nagpur': 250,
            'Thane': 800,
            'Nashik': 750,
            'Aurangabad': 370,
            'Solapur': 590,
            'Kolhapur': 760,
            'Amravati': 100,
            'Navi Mumbai': 870,
            'Jalgaon': 250,
            'Latur': 320,
            'Dhule': 375,
            'Nanded': 290,
            'Sangli': 760,
            'Malegaon': 600,
            'Jalna': 270,
            'Chandrapur': 560,
            'Bhiwandi': 880,
            'Parbhani': 190,
            'Ichalkaranji': 790,
            'Panvel': 890,
            'Satara': 720,
            'Beed': 430,
            'Yavatmal': 190,
            'Osmanabad': 610,
            'Ratnagiri': 1030,
            'Wardha': 360,
            'Buldhana': 120,
            'Gondia': 480,
            'Hingoli': 470,
            'Khopoli': 900,
            'Nandurbar': 690,
            'Palghar': 890,
            'Washim': 170,
            'Karad': 850,
            'Baramati': 730,
            'Chimur': 100,
            'Deolali': 890,
            'Gangapur': 930,
            'Junnar': 860,
            'Kamthi': 250,
            'Panjim': 1140,
        },
        'Jalgaon': {
            'Jalgaon': 0,
            'Mumbai': 410,
            'Pune': 450,
            'Nagpur': 460,
            'Thane': 250,
            'Nashik': 200,
            'Aurangabad': 250,
            'Solapur': 550,
            'Kolhapur': 850,
            'Amravati': 400,
            'Navi Mumbai': 690,
            'Akola': 250,
            'Latur': 530,
            'Dhule': 160,
            'Nanded': 690,
            'Sangli': 600,
            'Malegaon': 150,
            'Jalna': 220,
            'Chandrapur': 640,
            'Bhiwandi': 290,
            'Parbhani': 600,
            'Ichalkaranji': 590,
            'Panvel': 390,
            'Satara': 600,
            'Beed': 420,
            'Yavatmal': 700,
            'Osmanabad': 560,
            'Ratnagiri': 1000,
            'Wardha': 590,
            'Buldhana': 120,
            'Gondia': 850,
            'Hingoli': 400,
            'Khopoli': 830,
            'Nandurbar': 440,
            'Palghar': 410,
            'Washim': 170,
            'Karad': 800,
            'Baramati': 680,
            'Chimur': 640,
            'Deolali': 440,
            'Gangapur': 200,
            'Junnar': 420,
            'Kamthi': 450,
            'Panjim': 985,
        },
        'Latur': {
            'Latur': 0,
            'Mumbai': 520,
            'Pune': 300,
            'Nagpur': 570,
            'Thane': 750,
            'Nashik': 500,
            'Aurangabad': 250,
            'Solapur': 250,
            'Kolhapur': 680,
            'Amravati': 470,
            'Navi Mumbai': 750,
            'Akola': 320,
            'Jalgaon': 530,
            'Dhule': 450,
            'Nanded': 150,
            'Sangli': 610,
            'Malegaon': 720,
            'Jalna': 190,
            'Chandrapur': 690,
            'Bhiwandi': 680,
            'Parbhani': 60,
            'Ichalkaranji': 610,
            'Panvel': 750,
            'Satara': 400,
            'Beed': 110,
            'Yavatmal': 480,
            'Osmanabad': 150,
            'Ratnagiri': 910,
            'Wardha': 580,
            'Buldhana': 170,
            'Gondia': 800,
            'Hingoli': 360,
            'Khopoli': 720,
            'Nandurbar': 620,
            'Palghar': 710,
            'Washim': 550,
            'Karad': 380,
            'Baramati': 260,
            'Chimur': 540,
            'Deolali': 810,
            'Gangapur': 510,
            'Junnar': 340,
            'Kamthi': 720,
            'Panjim': 640,
        },
        'Dhule': {
            'Dhule': 0,
            'Mumbai': 335,
            'Pune': 370,
            'Nagpur': 770,
            'Thane': 300,
            'Nashik': 200,
            'Aurangabad': 500,
            'Solapur': 635,
            'Kolhapur': 560,
            'Amravati': 490,
            'Navi Mumbai': 670,
            'Akola': 375,
            'Jalgaon': 160,
            'Latur': 450,
            'Nanded': 590,
            'Sangli': 600,
            'Malegaon': 150,
            'Jalna': 390,
            'Chandrapur': 600,
            'Bhiwandi': 580,
            'Parbhani': 470,
            'Ichalkaranji': 530,
            'Panvel': 590,
            'Satara': 530,
            'Beed': 460,
            'Yavatmal': 660,
            'Osmanabad': 450,
            'Ratnagiri': 810,
            'Wardha': 610,
            'Buldhana': 220,
            'Gondia': 750,
            'Hingoli': 290,
            'Khopoli': 560,
            'Nandurbar': 270,
            'Palghar': 405,
            'Washim': 310,
            'Karad': 480,
            'Baramati': 390,
            'Chimur': 630,
            'Deolali': 410,
            'Gangapur': 150,
            'Junnar': 330,
            'Kamthi': 780,
            'Panjim': 1050,
        },
        'Nanded': {
            'Nanded': 0,
            'Mumbai': 560,
            'Pune': 470,
            'Nagpur': 270,
            'Thane': 890,
            'Nashik': 770,
            'Aurangabad': 270,
            'Solapur': 270,
            'Kolhapur': 670,
            'Amravati': 360,
            'Navi Mumbai': 670,
            'Akola': 290,
            'Jalgaon': 690,
            'Latur': 150,
            'Dhule': 590,
            'Sangli': 480,
            'Malegaon': 620,
            'Jalna': 290,
            'Chandrapur': 580,
            'Bhiwandi': 760,
            'Parbhani': 120,
            'Ichalkaranji': 640,
            'Panvel': 790,
            'Satara': 380,
            'Beed': 190,
            'Yavatmal': 500,
            'Osmanabad': 220,
            'Ratnagiri': 810,
            'Wardha': 600,
            'Buldhana': 350,
            'Gondia': 780,
            'Hingoli': 200,
            'Khopoli': 780,
            'Nandurbar': 680,
            'Palghar': 690,
            'Washim': 540,
            'Karad': 370,
            'Baramati': 230,
            'Chimur': 290,
            'Deolali': 590,
            'Gangapur': 400,
            'Junnar': 230,
            'Kamthi': 290,
            'Panjim': 774,
        },
        'Sangli': {
            'Sangli': 0,
            'Mumbai': 390,
            'Pune': 230,
            'Nagpur': 970,
            'Thane': 920,
            'Nashik': 900,
            'Aurangabad': 500,
            'Solapur': 530,
            'Kolhapur': 240,
            'Amravati': 750,
            'Navi Mumbai': 880,
            'Akola': 760,
            'Jalgaon': 600,
            'Latur': 610,
            'Dhule': 600,
            'Nanded': 480,
            'Malegaon': 780,
            'Jalna': 490,
            'Chandrapur': 670,
            'Bhiwandi': 890,
            'Parbhani': 560,
            'Ichalkaranji': 10,
            'Panvel': 920,
            'Satara': 100,
            'Beed': 490,
            'Yavatmal': 850,
            'Osmanabad': 330,
            'Ratnagiri': 130,
            'Wardha': 920,
            'Buldhana': 340,
            'Gondia': 970,
            'Hingoli': 510,
            'Khopoli': 930,
            'Nandurbar': 620,
            'Palghar': 880,
            'Washim': 570,
            'Karad': 180,
            'Baramati': 340,
            'Chimur': 640,
            'Deolali': 820,
            'Gangapur': 610,
            'Junnar': 450,
            'Kamthi': 980,
            'Panjim': 230,
        },
        'Malegaon': {
            'Malegaon': 0,
            'Mumbai': 270,
            'Pune': 350,
            'Nagpur': 770,
            'Thane': 570,
            'Nashik': 570,
            'Aurangabad': 570,
            'Solapur': 620,
            'Kolhapur': 550,
            'Amravati': 620,
            'Navi Mumbai': 590,
            'Akola': 600,
            'Jalgaon': 150,
            'Latur': 720,
            'Dhule': 150,
            'Nanded': 620,
            'Sangli': 780,
            'Jalna': 430,
            'Chandrapur': 780,
            'Bhiwandi': 620,
            'Parbhani': 650,
            'Ichalkaranji': 780,
            'Panvel': 650,
            'Satara': 730,
            'Beed': 710,
            'Yavatmal': 880,
            'Osmanabad': 740,
            'Ratnagiri': 910,
            'Wardha': 570,
            'Buldhana': 480,
            'Gondia': 880,
            'Hingoli': 700,
            'Khopoli': 600,
            'Nandurbar': 380,
            'Palghar': 590,
            'Washim': 570,
            'Karad': 680,
            'Baramati': 530,
            'Chimur': 720,
            'Deolali': 520,
            'Gangapur': 150,
            'Junnar': 550,
            'Kamthi': 800,
            'Panjim': 1135,
        },
        'Jalna': {
            'Jalna': 0,
            'Mumbai': 415,
            'Pune': 290,
            'Nagpur': 530,
            'Thane': 610,
            'Nashik': 490,
            'Aurangabad': 150,
            'Solapur': 260,
            'Kolhapur': 560,
            'Amravati': 260,
            'Navi Mumbai': 810,
            'Akola': 270,
            'Jalgaon': 220,
            'Latur': 190,
            'Dhule': 380,
            'Nanded': 290,
            'Sangli': 490,
            'Malegaon': 430,
            'Chandrapur': 590,
            'Bhiwandi': 620,
            'Parbhani': 140,
            'Ichalkaranji': 610,
            'Panvel': 740,
            'Satara': 350,
            'Beed': 220,
            'Yavatmal': 520,
            'Osmanabad': 190,
            'Ratnagiri': 840,
            'Wardha': 560,
            'Buldhana': 320,
            'Gondia': 700,
            'Hingoli': 190,
            'Khopoli': 630,
            'Nandurbar': 530,
            'Palghar': 650,
            'Washim': 530,
            'Karad': 390,
            'Baramati': 270,
            'Chimur': 510,
            'Deolali': 650,
            'Gangapur': 410,
            'Junnar': 240,
            'Kamthi': 520,
            'Panjim': 725,
        },
        'Chandrapur': {
            'Chandrapur': 0,
            'Mumbai': 910,
            'Pune': 810,
            'Nagpur': 150,
            'Thane': 810,
            'Nashik': 860,
            'Aurangabad': 590,
            'Solapur': 590,
            'Kolhapur': 710,
            'Amravati': 200,
            'Navi Mumbai': 850,
            'Akola': 560,
            'Jalgaon': 640,
            'Latur': 690,
            'Dhule': 600,
            'Nanded': 580,
            'Sangli': 670,
            'Malegaon': 770,
            'Jalna': 590,
            'Bhiwandi': 890,
            'Parbhani': 430,
            'Ichalkaranji': 700,
            'Panvel': 830,
            'Satara': 700,
            'Beed': 590,
            'Yavatmal': 230,
            'Osmanabad': 660,
            'Ratnagiri': 1100,
            'Wardha': 420,
            'Buldhana': 560,
            'Gondia': 290,
            'Hingoli': 580,
            'Khopoli': 820,
            'Nandurbar': 830,
            'Palghar': 910,
            'Washim': 540,
            'Karad': 710,
            'Baramati': 590,
            'Chimur': 150,
            'Deolali': 630,
            'Gangapur': 420,
            'Junnar': 530,
            'Kamthi': 160,
            'Panjim': 1435,
        },
        'Bhiwandi': {
            'Bhiwandi': 0,
            'Mumbai': 40,
            'Pune': 150,
            'Nagpur': 970,
            'Thane': 30,
            'Nashik': 130,
            'Aurangabad': 520,
            'Solapur': 580,
            'Kolhapur': 810,
            'Amravati': 920,
            'Navi Mumbai': 15,
            'Akola': 880,
            'Jalgaon': 290,
            'Latur': 620,
            'Dhule': 580,
            'Nanded': 760,
            'Sangli': 890,
            'Malegaon': 620,
            'Jalna': 620,
            'Chandrapur': 890,
            'Parbhani': 680,
            'Ichalkaranji': 880,
            'Panvel': 15,
            'Satara': 740,
            'Beed': 650,
            'Yavatmal': 920,
            'Osmanabad': 730,
            'Ratnagiri': 1010,
            'Wardha': 930,
            'Buldhana': 850,
            'Gondia': 1010,
            'Hingoli': 750,
            'Khopoli': 45,
            'Nandurbar': 950,
            'Palghar': 45,
            'Washim': 830,
            'Karad': 880,
            'Baramati': 700,
            'Chimur': 880,
            'Deolali': 45,
            'Gangapur': 770,
            'Junnar': 145,
            'Kamthi': 970,
            'Panjim': 640,
        },
        'Parbhani': {
            'Parbhani': 0,
            'Mumbai': 590,
            'Pune': 520,
            'Nagpur': 280,
            'Thane': 780,
            'Nashik': 670,
            'Aurangabad': 210,
            'Solapur': 310,
            'Kolhapur': 670,
            'Amravati': 310,
            'Navi Mumbai': 690,
            'Akola': 190,
            'Jalgaon': 600,
            'Latur': 60,
            'Dhule': 470,
            'Nanded': 120,
            'Sangli': 560,
            'Malegaon': 650,
            'Jalna': 140,
            'Chandrapur': 430,
            'Bhiwandi': 680,
            'Ichalkaranji': 560,
            'Panvel': 790,
            'Satara': 450,
            'Beed': 170,
            'Yavatmal': 390,
            'Osmanabad': 140,
            'Ratnagiri': 810,
            'Wardha': 520,
            'Buldhana': 270,
            'Gondia': 710,
            'Hingoli': 90,
            'Khopoli': 680,
            'Nandurbar': 580,
            'Palghar': 690,
            'Washim': 540,
            'Karad': 380,
            'Baramati': 240,
            'Chimur': 310,
            'Deolali': 590,
            'Gangapur': 420,
            'Junnar': 250,
            'Kamthi': 320,
            'Panjim': 725,
        },
        'Ichalkaranji': {
            'Ichalkaranji': 0,
            'Mumbai': 840,
            'Pune': 730,
            'Nagpur': 810,
            'Thane': 870,
            'Nashik': 700,
            'Aurangabad': 510,
            'Solapur': 530,
            'Kolhapur': 260,
            'Amravati': 870,
            'Navi Mumbai': 880,
            'Akola': 790,
            'Jalgaon': 590,
            'Latur': 570,
            'Dhule': 620,
            'Nanded': 770,
            'Sangli': 10,
            'Malegaon': 780,
            'Jalna': 610,
            'Chandrapur': 720,
            'Bhiwandi': 880,
            'Parbhani': 560,
            'Panvel': 910,
            'Satara': 290,
            'Beed': 600,
            'Yavatmal': 970,
            'Osmanabad': 440,
            'Ratnagiri': 1100,
            'Wardha': 660,
            'Buldhana': 720,
            'Gondia': 820,
            'Hingoli': 600,
            'Khopoli': 860,
            'Nandurbar': 780,
            'Palghar': 940,
            'Washim': 720,
            'Karad': 270,
            'Baramati': 430,
            'Chimur': 810,
            'Deolali': 850,
            'Gangapur': 600,
            'Junnar': 740,
            'Kamthi': 810,
            'Panjim': 255,
        },
        'Panvel': {
            'Panvel': 0,
            'Mumbai': 40,
            'Pune': 150,
            'Nagpur': 910,
            'Thane': 40,
            'Nashik': 250,
            'Aurangabad': 635,
            'Solapur': 815,
            'Kolhapur': 905,
            'Amravati': 940,
            'Navi Mumbai': 40,
            'Akola': 890,
            'Jalgaon': 390,
            'Latur': 750,
            'Dhule': 590,
            'Nanded': 790,
            'Sangli': 920,
            'Malegaon': 650,
            'Jalna': 740,
            'Chandrapur': 830,
            'Bhiwandi': 15,
            'Parbhani': 790,
            'Ichalkaranji': 910,
            'Satara': 830,
            'Beed': 650,
            'Yavatmal': 920,
            'Osmanabad': 730,
            'Ratnagiri': 960,
            'Wardha': 890,
            'Buldhana': 820,
            'Gondia': 960,
            'Hingoli': 710,
            'Khopoli': 55,
            'Nandurbar': 910,
            'Palghar': 70,
            'Washim': 800,
            'Karad': 890,
            'Baramati': 710,
            'Chimur': 890,
            'Deolali': 70,
            'Gangapur': 760,
            'Junnar': 160,
            'Kamthi': 890,
            'Panjim': 585,
        },
        'Satara': {
            'Satara': 0,
            'Mumbai': 260,
            'Pune': 110,
            'Nagpur': 890,
            'Thane': 270,
            'Nashik': 500,
            'Aurangabad': 540,
            'Solapur': 240,
            'Kolhapur': 230,
            'Amravati': 780,
            'Navi Mumbai': 830,
            'Akola': 720,
            'Jalgaon': 600,
            'Latur': 380,
            'Dhule': 530,
            'Nanded': 550,
            'Sangli': 100,
            'Malegaon': 730,
            'Jalna': 350,
            'Chandrapur': 670,
            'Bhiwandi': 740,
            'Parbhani': 400,
            'Ichalkaranji': 340,
            'Panvel': 830,
            'Beed': 360,
            'Yavatmal': 710,
            'Osmanabad': 180,
            'Ratnagiri': 250,
            'Wardha': 790,
            'Buldhana': 430,
            'Gondia': 950,
            'Hingoli': 480,
            'Khopoli': 760,
            'Nandurbar': 690,
            'Palghar': 750,
            'Washim': 630,
            'Karad': 80,
            'Baramati': 240,
            'Chimur': 840,
            'Deolali': 600,
            'Gangapur': 330,
            'Junnar': 160,
            'Kamthi': 890,
            'Panjim': 265,
        },
        'Beed': {
            'Beed': 0,
            'Mumbai': 510,
            'Pune': 390,
            'Nagpur': 600,
            'Thane': 690,
            'Nashik': 490,
            'Aurangabad': 200,
            'Solapur': 200,
            'Kolhapur': 680,
            'Amravati': 570,
            'Navi Mumbai': 650,
            'Akola': 430,
            'Jalgaon': 420,
            'Latur': 110,
            'Dhule': 460,
            'Nanded': 190,
            'Sangli': 490,
            'Malegaon': 710,
            'Jalna': 220,
            'Chandrapur': 590,
            'Bhiwandi': 650,
            'Parbhani': 170,
            'Ichalkaranji': 600,
            'Panvel': 650,
            'Satara': 360,
            'Yavatmal': 390,
            'Osmanabad': 150,
            'Ratnagiri': 910,
            'Wardha': 580,
            'Buldhana': 170,
            'Gondia': 810,
            'Hingoli': 360,
            'Khopoli': 610,
            'Nandurbar': 550,
            'Palghar': 690,
            'Washim': 530,
            'Karad': 220,
            'Baramati': 160,
            'Chimur': 540,
            'Deolali': 810,
            'Gangapur': 410,
            'Junnar': 340,
            'Kamthi': 570,
            'Panjim': 640,
        },
        'Yavatmal': {
            'Yavatmal': 0,
            'Mumbai': 790,
            'Pune': 670,
            'Nagpur': 160,
            'Thane': 920,
            'Nashik': 670,
            'Aurangabad': 490,
            'Solapur': 800,
            'Kolhapur': 990,
            'Amravati': 150,
            'Navi Mumbai': 920,
            'Akola': 190,
            'Jalgaon': 700,
            'Latur': 480,
            'Dhule': 660,
            'Nanded': 500,
            'Sangli': 850,
            'Malegaon': 880,
            'Jalna': 520,
            'Chandrapur': 230,
            'Bhiwandi': 920,
            'Parbhani': 390,
            'Ichalkaranji': 970,
            'Panvel': 920,
            'Satara': 710,
            'Beed': 390,
            'Osmanabad': 420,
            'Ratnagiri': 1020,
            'Wardha': 510,
            'Buldhana': 320,
            'Gondia': 610,
            'Hingoli': 290,
            'Khopoli': 900,
            'Nandurbar': 800,
            'Palghar': 810,
            'Washim': 660,
            'Karad': 570,
            'Baramati': 680,
            'Chimur': 240,
            'Deolali': 710,
            'Gangapur': 520,
            'Junnar': 290,
            'Kamthi': 270,
            'Panjim': 1345,
        },
        'Osmanabad': {
            'Osmanabad': 0,
            'Mumbai': 640,
            'Pune': 520,
            'Nagpur': 530,
            'Thane': 720,
            'Nashik': 580,
            'Aurangabad': 260,
            'Solapur': 140,
            'Kolhapur': 790,
            'Amravati': 460,
            'Navi Mumbai': 720,
            'Akola': 300,
            'Jalgaon': 560,
            'Latur': 150,
            'Dhule': 450,
            'Nanded': 220,
            'Sangli': 330,
            'Malegaon': 540,
            'Jalna': 190,
            'Chandrapur': 660,
            'Bhiwandi': 730,
            'Parbhani': 140,
            'Ichalkaranji': 730,
            'Panvel': 730,
            'Satara': 530,
            'Beed': 220,
            'Yavatmal': 420,
            'Ratnagiri': 780,
            'Wardha': 630,
            'Buldhana': 380,
            'Gondia': 750,
            'Hingoli': 180,
            'Khopoli': 650,
            'Nandurbar': 540,
            'Palghar': 660,
            'Washim': 510,
            'Karad': 340,
            'Baramati': 420,
            'Chimur': 530,
            'Deolali': 610,
            'Gangapur': 370,
            'Junnar': 200,
            'Kamthi': 560,
            'Panjim': 525,
        },
        'Ratnagiri': {
            'Ratnagiri': 0,
            'Mumbai': 330,
            'Pune': 400,
            'Nagpur': 1010,
            'Thane': 320,
            'Nashik': 630,
            'Aurangabad': 870,
            'Solapur': 920,
            'Kolhapur': 70,
            'Amravati': 1160,
            'Navi Mumbai': 330,
            'Akola': 1080,
            'Jalgaon': 1000,
            'Latur': 910,
            'Dhule': 810,
            'Nanded': 1010,
            'Sangli': 130,
            'Malegaon': 1110,
            'Jalna': 840,
            'Chandrapur': 1100,
            'Bhiwandi': 1010,
            'Parbhani': 810,
            'Ichalkaranji': 1100,
            'Panvel': 960,
            'Satara': 250,
            'Beed': 910,
            'Yavatmal': 1020,
            'Osmanabad': 780,
            'Wardha': 1140,
            'Buldhana': 1090,
            'Gondia': 1190,
            'Hingoli': 880,
            'Khopoli': 850,
            'Nandurbar': 1290,
            'Palghar': 240,
            'Washim': 1130,
            'Karad': 100,
            'Baramati': 310,
            'Chimur': 1200,
            'Deolali': 320,
            'Gangapur': 920,
            'Junnar': 300,
            'Kamthi': 1010,
            'Panjim': 235,
        },
        'Wardha': {
            'Wardha': 0,
            'Mumbai': 710,
            'Pune': 640,
            'Nagpur': 110,
            'Thane': 730,
            'Nashik': 630,
            'Aurangabad': 490,
            'Solapur': 560,
            'Kolhapur': 820,
            'Amravati': 170,
            'Navi Mumbai': 720,
            'Akola': 250,
            'Jalgaon': 590,
            'Latur': 560,
            'Dhule': 610,
            'Nanded': 600,
            'Sangli': 910,
            'Malegaon': 590,
            'Jalna': 550,
            'Chandrapur': 420,
            'Bhiwandi': 930,
            'Parbhani': 510,
            'Ichalkaranji': 660,
            'Panvel': 890,
            'Satara': 680,
            'Beed': 580,
            'Yavatmal': 510,
            'Osmanabad': 630,
            'Ratnagiri': 1140,
            'Buldhana': 350,
            'Gondia': 200,
            'Hingoli': 350,
            'Khopoli': 890,
            'Nandurbar': 820,
            'Palghar': 730,
            'Washim': 480,
            'Karad': 750,
            'Baramati': 530,
            'Chimur': 530,
            'Deolali': 570,
            'Gangapur': 360,
            'Junnar': 580,
            'Kamthi': 240,
            'Panjim': 1260,
        },
        'Buldhana': {
            'Buldhana': 0,
            'Mumbai': 530,
            'Pune': 460,
            'Nagpur': 750,
            'Thane': 540,
            'Nashik': 330,
            'Aurangabad': 580,
            'Solapur': 640,
            'Kolhapur': 740,
            'Amravati': 250,
            'Navi Mumbai': 560,
            'Akola': 110,
            'Jalgaon': 120,
            'Latur': 170,
            'Dhule': 220,
            'Nanded': 350,
            'Sangli': 340,
            'Malegaon': 480,
            'Jalna': 320,
            'Chandrapur': 520,
            'Bhiwandi': 870,
            'Parbhani': 270,
            'Ichalkaranji': 720,
            'Panvel': 820,
            'Satara': 550,
            'Beed': 270,
            'Yavatmal': 400,
            'Osmanabad': 390,
            'Ratnagiri': 1090,
            'Wardha': 480,
            'Gondia': 860,
            'Hingoli': 250,
            'Khopoli': 800,
            'Nandurbar': 520,
            'Palghar': 720,
            'Washim': 300,
            'Karad': 520,
            'Baramati': 310,
            'Chimur': 620,
            'Deolali': 470,
            'Gangapur': 230,
            'Junnar': 450,
            'Kamthi': 770,
            'Panjim': 1160,
        },
        'Gondia': {
            'Gondia': 0,
            'Mumbai': 1080,
            'Pune': 1000,
            'Nagpur': 150,
            'Thane': 1080,
            'Nashik': 1030,
            'Aurangabad': 670,
            'Solapur': 760,
            'Kolhapur': 950,
            'Amravati': 200,
            'Navi Mumbai': 1070,
            'Akola': 490,
            'Jalgaon': 790,
            'Latur': 790,
            'Dhule': 900,
            'Nanded': 770,
            'Sangli': 970,
            'Malegaon': 880,
            'Jalna': 700,
            'Chandrapur': 290,
            'Bhiwandi': 1010,
            'Parbhani': 710,
            'Ichalkaranji': 820,
            'Panvel': 1040,
            'Satara': 950,
            'Beed': 810,
            'Yavatmal': 610,
            'Osmanabad': 750,
            'Ratnagiri': 1190,
            'Wardha': 220,
            'Buldhana': 810,
            'Hingoli': 830,
            'Khopoli': 1080,
            'Nandurbar': 1170,
            'Palghar': 1150,
            'Washim': 890,
            'Karad': 1010,
            'Baramati': 890,
            'Chimur': 180,
            'Deolali': 800,
            'Gangapur': 660,
            'Junnar': 950,
            'Kamthi': 250,
            'Panjim': 1425,
        },
        'Hingoli': {
            'Hingoli': 0,
            'Mumbai': 600,
            'Pune': 530,
            'Nagpur': 340,
            'Thane': 640,
            'Nashik': 520,
            'Aurangabad': 150,
            'Solapur': 280,
            'Kolhapur': 730,
            'Amravati': 330,
            'Navi Mumbai': 640,
            'Akola': 200,
            'Jalgaon': 430,
            'Latur': 90,
            'Dhule': 370,
            'Nanded': 80,
            'Sangli': 510,
            'Malegaon': 700,
            'Jalna': 190,
            'Chandrapur': 590,
            'Bhiwandi': 750,
            'Parbhani': 90,
            'Ichalkaranji': 600,
            'Panvel': 710,
            'Satara': 480,
            'Beed': 360,
            'Yavatmal': 300,
            'Osmanabad': 180,
            'Ratnagiri': 880,
            'Wardha': 420,
            'Buldhana': 250,
            'Gondia': 830,
            'Khopoli': 670,
            'Nandurbar': 570,
            'Palghar': 680,
            'Washim': 330,
            'Karad': 470,
            'Baramati': 320,
            'Chimur': 420,
            'Deolali': 500,
            'Gangapur': 320,
            'Junnar': 320,
            'Kamthi': 400,
            'Panjim': 900,
        },
        'Khopoli': {
            'Khopoli': 0,
            'Mumbai': 85,
            'Pune': 100,
            'Nagpur': 1030,
            'Thane': 85,
            'Nashik': 330,
            'Aurangabad': 685,
            'Solapur': 865,
            'Kolhapur': 855,
            'Amravati': 940,
            'Navi Mumbai': 85,
            'Akola': 890,
            'Jalgaon': 400,
            'Latur': 760,
            'Dhule': 600,
            'Nanded': 800,
            'Sangli': 930,
            'Malegaon': 600,
            'Jalna': 690,
            'Chandrapur': 820,
            'Bhiwandi': 30,
            'Parbhani': 690,
            'Ichalkaranji': 860,
            'Panvel': 10,
            'Satara': 840,
            'Beed': 610,
            'Yavatmal': 900,
            'Osmanabad': 710,
            'Ratnagiri': 850,
            'Wardha': 890,
            'Buldhana': 800,
            'Gondia': 1080,
            'Hingoli': 670,
            'Nandurbar': 910,
            'Palghar': 70,
            'Washim': 830,
            'Karad': 920,
            'Baramati': 740,
            'Chimur': 950,
            'Deolali': 70,
            'Gangapur': 780,
            'Junnar': 170,
            'Kamthi': 1030,
            'Panjim': 565,
        },
        'Nandurbar': {
            'Nandurbar': 0,
            'Mumbai': 610,
            'Pune': 540,
            'Nagpur': 1080,
            'Thane': 620,
            'Nashik': 310,
            'Aurangabad': 720,
            'Solapur': 790,
            'Kolhapur': 800,
            'Amravati': 330,
            'Navi Mumbai': 570,
            'Akola': 420,
            'Jalgaon': 160,
            'Latur': 470,
            'Dhule': 170,
            'Nanded': 470,
            'Sangli': 480,
            'Malegaon': 490,
            'Jalna': 450,
            'Chandrapur': 830,
            'Bhiwandi': 950,
            'Parbhani': 580,
            'Ichalkaranji': 780,
            'Panvel': 900,
            'Satara': 690,
            'Beed': 550,
            'Yavatmal': 800,
            'Osmanabad': 540,
            'Ratnagiri': 1290,
            'Wardha': 820,
            'Buldhana': 520,
            'Gondia': 1170,
            'Hingoli': 570,
            'Khopoli': 910,
            'Palghar': 730,
            'Washim': 400,
            'Karad': 660,
            'Baramati': 450,
            'Chimur': 1010,
            'Deolali': 540,
            'Gangapur': 320,
            'Junnar': 540,
            'Kamthi': 1080,
            'Panjim': 1145,
        },
        'Palghar': {
            'Palghar': 0,
            'Mumbai': 85,
            'Pune': 150,
            'Nagpur': 1070,
            'Thane': 85,
            'Nashik': 210,
            'Aurangabad': 595,
            'Solapur': 775,
            'Kolhapur': 865,
            'Amravati': 900,
            'Navi Mumbai': 85,
            'Akola': 850,
            'Jalgaon': 350,
            'Latur': 710,
            'Dhule': 550,
            'Nanded': 750,
            'Sangli': 880,
            'Malegaon': 610,
            'Jalna': 700,
            'Chandrapur': 790,
            'Bhiwandi': 30,
            'Parbhani': 690,
            'Ichalkaranji': 910,
            'Panvel': 30,
            'Satara': 830,
            'Beed': 670,
            'Yavatmal': 810,
            'Osmanabad': 660,
            'Ratnagiri': 940,
            'Wardha': 730,
            'Buldhana': 720,
            'Gondia': 1150,
            'Hingoli': 680,
            'Khopoli': 70,
            'Nandurbar': 730,
            'Washim': 840,
            'Karad': 880,
            'Baramati': 700,
            'Chimur': 910,
            'Deolali': 70,
            'Gangapur': 750,
            'Junnar': 190,
            'Kamthi': 940,
            'Panjim': 670,
        },
        'Washim': {
            'Washim': 0,
            'Mumbai': 750,
            'Pune': 630,
            'Nagpur': 610,
            'Thane': 780,
            'Nashik': 560,
            'Aurangabad': 290,
            'Solapur': 160,
            'Kolhapur': 810,
            'Amravati': 390,
            'Navi Mumbai': 770,
            'Akola': 170,
            'Jalgaon': 520,
            'Latur': 180,
            'Dhule': 360,
            'Nanded': 300,
            'Sangli': 650,
            'Malegaon': 720,
            'Jalna': 310,
            'Chandrapur': 540,
            'Bhiwandi': 830,
            'Parbhani': 540,
            'Ichalkaranji': 720,
            'Panvel': 800,
            'Satara': 630,
            'Beed': 530,
            'Yavatmal': 660,
            'Osmanabad': 510,
            'Ratnagiri': 1130,
            'Wardha': 480,
            'Buldhana': 300,
            'Gondia': 890,
            'Hingoli': 330,
            'Khopoli': 830,
            'Nandurbar': 400,
            'Palghar': 830,
            'Karad': 630,
            'Baramati': 510,
            'Chimur': 610,
            'Deolali': 780,
            'Gangapur': 330,
            'Junnar': 560,
            'Kamthi': 610,
            'Panjim': 1175,
        },
        'Karad': {
            'Karad': 0,
            'Mumbai': 270,
            'Pune': 180,
            'Nagpur': 990,
            'Thane': 280,
            'Nashik': 510,
            'Aurangabad': 420,
            'Solapur': 150,
            'Kolhapur': 120,
            'Amravati': 770,
            'Navi Mumbai': 810,
            'Akola': 690,
            'Jalgaon': 560,
            'Latur': 310,
            'Dhule': 460,
            'Nanded': 480,
            'Sangli': 110,
            'Malegaon': 700,
            'Jalna': 320,
            'Chandrapur': 710,
            'Bhiwandi': 880,
            'Parbhani': 380,
            'Ichalkaranji': 270,
            'Panvel': 890,
            'Satara': 80,
            'Beed': 220,
            'Yavatmal': 570,
            'Osmanabad': 340,
            'Ratnagiri': 100,
            'Wardha': 750,
            'Buldhana': 460,
            'Gondia': 1010,
            'Hingoli': 470,
            'Khopoli': 920,
            'Nandurbar': 660,
            'Palghar': 880,
            'Washim': 630,
            'Baramati': 180,
            'Chimur': 1020,
            'Deolali': 310,
            'Gangapur': 120,
            'Junnar': 240,
            'Kamthi': 1000,
            'Panjim': 240,
        },
        'Baramati': {
            'Baramati': 0,
            'Mumbai': 230,
            'Pune': 120,
            'Nagpur': 920,
            'Thane': 240,
            'Nashik': 470,
            'Aurangabad': 380,
            'Solapur': 190,
            'Kolhapur': 250,
            'Amravati': 720,
            'Navi Mumbai': 760,
            'Akola': 640,
            'Jalgaon': 510,
            'Latur': 270,
            'Dhule': 420,
            'Nanded': 440,
            'Sangli': 170,
            'Malegaon': 660,
            'Jalna': 280,
            'Chandrapur': 670,
            'Bhiwandi': 850,
            'Parbhani': 350,
            'Ichalkaranji': 240,
            'Panvel': 890,
            'Satara': 240,
            'Beed': 160,
            'Yavatmal': 680,
            'Osmanabad': 420,
            'Ratnagiri': 310,
            'Wardha': 530,
            'Buldhana': 310,
            'Gondia': 890,
            'Hingoli': 320,
            'Khopoli': 740,
            'Nandurbar': 450,
            'Palghar': 700,
            'Washim': 510,
            'Karad': 180,
            'Chimur': 980,
            'Deolali': 240,
            'Gangapur': 130,
            'Junnar': 230,
            'Kamthi': 950,
            'Panjim': 410,
        },
        'Chimur': {
            'Chimur': 0,
            'Mumbai': 1070,
            'Pune': 990,
            'Nagpur': 190,
            'Thane': 1070,
            'Nashik': 1020,
            'Aurangabad': 660,
            'Solapur': 750,
            'Kolhapur': 940,
            'Amravati': 190,
            'Navi Mumbai': 1060,
            'Akola': 490,
            'Jalgaon': 790,
            'Latur': 800,
            'Dhule': 910,
            'Nanded': 780,
            'Sangli': 980,
            'Malegaon': 890,
            'Jalna': 710,
            'Chandrapur': 170,
            'Bhiwandi': 1030,
            'Parbhani': 730,
            'Ichalkaranji': 840,
            'Panvel': 1090,
            'Satara': 840,
            'Beed': 540,
            'Yavatmal': 240,
            'Osmanabad': 530,
            'Ratnagiri': 1200,
            'Wardha': 530,
            'Buldhana': 620,
            'Gondia': 180,
            'Hingoli': 420,
            'Khopoli': 950,
            'Nandurbar': 1010,
            'Palghar': 910,
            'Washim': 610,
            'Karad': 1020,
            'Baramati': 980,
            'Deolali': 960,
            'Gangapur': 820,
            'Junnar': 980,
            'Kamthi': 190,
            'Panjim': 1245,
        },
        'Deolali': {
            'Deolali': 0,
            'Mumbai': 910,
            'Pune': 830,
            'Nagpur': 310,
            'Thane': 910,
            'Nashik': 860,
            'Aurangabad': 500,
            'Solapur': 670,
            'Kolhapur': 870,
            'Amravati': 310,
            'Navi Mumbai': 900,
            'Akola': 420,
            'Jalgaon': 720,
            'Latur': 710,
            'Dhule': 820,
            'Nanded': 690,
            'Sangli': 890,
            'Malegaon': 800,
            'Jalna': 620,
            'Chandrapur': 170,
            'Bhiwandi': 930,
            'Parbhani': 630,
            'Ichalkaranji': 740,
            'Panvel': 960,
            'Satara': 600,
            'Beed': 810,
            'Yavatmal': 710,
            'Osmanabad': 460,
            'Ratnagiri': 320,
            'Wardha': 570,
            'Buldhana': 470,
            'Gondia': 800,
            'Hingoli': 460,
            'Khopoli': 970,
            'Nandurbar': 540,
            'Palghar': 910,
            'Washim': 670,
            'Karad': 310,
            'Baramati': 240,
            'Chimur': 980,
            'Gangapur': 760,
            'Junnar': 800,
            'Kamthi': 310,
            'Panjim': 665,
        },
        'Gangapur': {
            'Gangapur': 0,
            'Mumbai': 760,
            'Pune': 680,
            'Nagpur': 490,
            'Thane': 760,
            'Nashik': 710,
            'Aurangabad': 350,
            'Solapur': 520,
            'Kolhapur': 720,
            'Amravati': 400,
            'Navi Mumbai': 750,
            'Akola': 270,
            'Jalgaon': 580,
            'Latur': 580,
            'Dhule': 690,
            'Nanded': 560,
            'Sangli': 760,
            'Malegaon': 670,
            'Jalna': 500,
            'Chandrapur': 620,
            'Bhiwandi': 820,
            'Parbhani': 570,
            'Ichalkaranji': 680,
            'Panvel': 760,
            'Satara': 330,
            'Beed': 410,
            'Yavatmal': 520,
            'Osmanabad': 370,
            'Ratnagiri': 920,
            'Wardha': 360,
            'Buldhana': 230,
            'Gondia': 660,
            'Hingoli': 320,
            'Khopoli': 780,
            'Nandurbar': 320,
            'Palghar': 750,
            'Washim': 540,
            'Karad': 120,
            'Baramati': 130,
            'Chimur': 820,
            'Deolali': 760,
            'Junnar': 510,
            'Kamthi': 660,
            'Panjim': 590,
        },
        'Junnar': {
            'Junnar': 0,
            'Mumbai': 220,
            'Pune': 110,
            'Nagpur': 1010,
            'Thane': 220,
            'Nashik': 450,
            'Aurangabad': 360,
            'Solapur': 190,
            'Kolhapur': 270,
            'Amravati': 810,
            'Navi Mumbai': 830,
            'Akola': 710,
            'Jalgaon': 580,
            'Latur': 350,
            'Dhule': 500,
            'Nanded': 520,
            'Sangli': 80,
            'Malegaon': 670,
            'Jalna': 290,
            'Chandrapur': 680,
            'Bhiwandi': 890,
            'Parbhani': 390,
            'Ichalkaranji': 280,
            'Panvel': 900,
            'Satara': 140,
            'Beed': 260,
            'Yavatmal': 740,
            'Osmanabad': 200,
            'Ratnagiri': 300,
            'Wardha': 580,
            'Buldhana': 450,
            'Gondia': 950,
            'Hingoli': 320,
            'Khopoli': 790,
            'Nandurbar': 540,
            'Palghar': 860,
            'Washim': 610,
            'Karad': 240,
            'Baramati': 150,
            'Chimur': 980,
            'Deolali': 230,
            'Gangapur': 550,
            'Kamthi': 1010,
            'Panjim': 425,
        },
        'Kamthi': {
            'Kamthi': 0,
            'Mumbai': 1010,
            'Pune': 930,
            'Nagpur': 0,
            'Thane': 1010,
            'Nashik': 960,
            'Aurangabad': 700,
            'Solapur': 790,
            'Kolhapur': 980,
            'Amravati': 290,
            'Navi Mumbai': 1030,
            'Akola': 630,
            'Jalgaon': 930,
            'Latur': 910,
            'Dhule': 1020,
            'Nanded': 890,
            'Sangli': 1090,
            'Malegaon': 1000,
            'Jalna': 820,
            'Chandrapur': 0,
            'Bhiwandi': 1050,
            'Parbhani': 850,
            'Ichalkaranji': 960,
            'Panvel': 1070,
            'Satara': 850,
            'Beed': 760,
            'Yavatmal': 220,
            'Osmanabad': 560,
            'Ratnagiri': 1010,
            'Wardha': 290,
            'Buldhana': 770,
            'Gondia': 250,
            'Hingoli': 400,
            'Khopoli': 1030,
            'Nandurbar': 1080,
            'Palghar': 940,
            'Washim': 610,
            'Karad': 1000,
            'Baramati': 950,
            'Chimur': 190,
            'Deolali': 410,
            'Gangapur': 600,
            'Junnar': 1000,
            'Panjim': 1415,
        },
        'Panjim': {
            'Mumbai': 590,
            'Pune': 440,
            'Nagpur': 1050,
            'Thane': 580,
            'Nashik': 660,
            'Aurangabad': 560,
            'Solapur': 485,
            'Kolhapur': 200,
            'Amravati': 1245,
            'Navi Mumbai': 590,
            'Akola': 1140,
            'Jalgaon': 985,
            'Latur': 640,
            'Dhule': 1050,
            'Nanded': 774,
            'Sangli': 230,
            'Malegaon': 1135,
            'Jalna': 725,
            'Chandrapur': 1435,
            'Bhiwandi': 640,
            'Parbhani': 725,
            'Ichalkaranji': 255,
            'Panvel': 585,
            'Satara': 265,
            'Beed': 640,
            'Yavatmal': 1345,
            'Osmanabad': 525,
            'Ratnagiri': 235,
            'Wardha': 1260,
            'Buldhana': 1160,
            'Gondia': 1425,
            'Hingoli': 900,
            'Khopoli': 565,
            'Nandurbar': 1145,
            'Palghar': 670,
            'Washim': 1175,
            'Karad': 240,
            'Baramati': 410,
            'Chimur': 1245,
            'Deolali': 665,
            'Gangapur': 590,
            'Junnar': 425,
            'Kamthi': 1415,
            'Panjim': 0
        }
    };

    // Get the predefined distance based on the selected source and destination cities
    let roundOffDistance = predefinedDistances[sourceCity][destinationCity];
    let totalDistance = predefinedDistances[sourceCity][destinationCity];

    // Apply rounding logic based on thresholds
    if (totalDistance < 300) {
        roundOffDistance = 300;
    } else if (totalDistance >= 300 && totalDistance < 600) {
        roundOffDistance = 600;
    } else if (totalDistance >= 600 && totalDistance < 900) {
        roundOffDistance = 900;
    } else if (totalDistance >= 900 && totalDistance < 1200) {
        roundOffDistance = 1200;
    }// Add more thresholds as needed

    sorceDestinationNames = [sourceCity, destinationCity]
    var bothDistanceArray = [roundOffDistance, totalDistance, sorceDestinationNames];

    console.log("Booking from " + sourceCity + " to " + destinationCity + " is under process");

    return bothDistanceArray;
}


function confirmBooking(cabType, fare, nameInputId, mobileNumberInputId, distanceValue) {

    var fullNameInput = document.getElementById(nameInputId);
    var mobileNumberInput = document.getElementById(mobileNumberInputId);

    var fullName = fullNameInput.value;
    var mobileNumber = mobileNumberInput.value;
    var sourceCity = document.getElementById('source').value;
    var destinationCity = document.getElementById('destination').value;

    var confirmationMessage = `Booking confirmed, Our executive will call you soon for payment and other details.Please check booking details. \n\nBooking Details:\nCab Type: ${cabType}\nFare: ${fare}\nPassanger Name : ${fullName}\nMobile Number: ${mobileNumber}`;



    console.log('Booking Confirmed:', cabType, fare, fullName, mobileNumber, distanceValue, sourceCity, destinationCity);

    alert(confirmationMessage);
    // Comented below code for testing purpose
    // sendSMS(fullName, mobileNumber, cabType, fare, sourceCity, destinationCity);
    closeModal();
}

function closeModal() {
    var modal = document.getElementById('myModal');
    modal.style.display = 'none';
}


// Add other functions as needed

document.addEventListener('DOMContentLoaded', function () {
    function toggleMenu() {
        var menuOptions = document.getElementById('menuOptions');
        menuOptions.style.display = menuOptions.style.display === 'flex' ? 'none' : 'flex';
    }

    function closeMenuOnClickOutside(event) {
        var menuOptions = document.getElementById('menuOptions');
        var burgerMenu = document.getElementById('burgerMenu');

        if (!menuOptions.contains(event.target) && !burgerMenu.contains(event.target)) {
            menuOptions.style.display = 'none';
        }
    }

    document.getElementById('burgerMenu').addEventListener('click', toggleMenu);

    document.querySelectorAll('.menu-options a').forEach(function (link) {
        link.addEventListener('click', function (event) {
            event.preventDefault();
            var sectionId = this.getAttribute('href').substring(1);
            scrollToSection(sectionId);
        });
    });

    function scrollToSection(sectionId) {
        var targetSection = document.getElementById(sectionId);
        if (targetSection) {
            window.scrollTo({
                top: targetSection.offsetTop,
                behavior: 'smooth'
            });

            toggleMenu();
        }
    }
});

function closeErrorModal() {
    var modal = document.getElementById('errorModal');
    modal.style.display = 'none';
}

// Function to format date in YYYY-MM-DD
function formatDate(date) {
    var year = date.getFullYear();
    var month = (date.getMonth() + 1).toString().padStart(2, '0');
    var day = (date.getDate()).toString().padStart(2, '0');
    return `${year}-${month}-${day}`;
}

// Set default value for the travelDate input
var currentDate = new Date();
currentDate.setDate(currentDate.getDate() + 1);
document.getElementById('travelDate').value = formatDate(currentDate);


function sendSMS(fullName, bookingMobileNumber, cabType, fare, sourceCity, destinationCity) {
    const accountSid = 'AC58b91b8fa290981736d03c4bf11afda2';
    const authToken = 'f78c89ee5721ba68d6b84f1a7f0306ec';
    const twilioNumber = '+15344446492';
    const ownerNumber = '+919922333305';
    const customerNumber = "+91" + bookingMobileNumber;

    // const userMessage = 'Thank You ' + fullName + ' for booking ride with Indian Cabbi. Our Team will further cordinate with you for more details and preference. Please check the booking Details : Passanger Name : ' + fullName + ' Contact information is ' + customerNumber + '';

    const ownerMessage = 'Booking confirmed. Please check the booking Details : Passanger Name : ' + fullName + ' Mobile Number ' + customerNumber + ' Cab Type selected ' + cabType + ' Total Fare: ' + fare + ' Travelling from ' + sourceCity + ' to ' + destinationCity;


    console.log("Message details is " + ownerMessage)

    const apiUrl = `https://api.twilio.com/2010-04-01/Accounts/AC58b91b8fa290981736d03c4bf11afda2/Messages.json`;

    // Construct the request
    fetch(apiUrl, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Authorization': 'Basic ' + btoa(`AC58b91b8fa290981736d03c4bf11afda2:f78c89ee5721ba68d6b84f1a7f0306ec`)
        },
        body: new URLSearchParams({
            From: twilioNumber,
            To: ownerNumber,
            Body: ownerMessage,
        })
    })
        .then(response => response.json())
        .then(data => {
            console.log('SMS sent successfully:', data);
            // Handle success, update UI, etc.
        })
        .catch(error => {
            console.error('Error sending SMS:', error);
            // Handle error, display error message, etc.
        });
}
// Function to open WhatsApp with a predefined message
function openWhatsApp() {
    // Get all elements with the class 'whatsapp-link'
    var whatsappLinks = document.querySelectorAll('.whatsapp-link');

    // Loop through each link
    whatsappLinks.forEach(function (link) {
        // Get the phone number from the data attribute
        var phoneNumber = link.getAttribute('data-phone');

        // Get the message you want to send (replace with your own)
        var message = "Hi Axis cabs, Need some help to book a cab in Delhi.";

        // Encode the message for the URL
        var encodedMessage = encodeURIComponent(message);

        // Create the WhatsApp link with the phone number and message
        var whatsappLink = "https://wa.me/" + phoneNumber + "?text=" + encodedMessage;

        // Set the href attribute of the WhatsApp link
        link.href = whatsappLink;
    });
}

// Call the function when the page loads
document.addEventListener("DOMContentLoaded", openWhatsApp);
